name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    environment: build_and_test_environment

    strategy:
      matrix:
        node-version: [15.x]
        # node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: create env file
      run: |
        touch .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test