name: Build, Lint, Format and Test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build_and_test_environment
    strategy:
      matrix:
        node-version: [16.x]
        # node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
          echo STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} >> .env
          echo MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} >> .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }} >> .env
          echo TEST_USER_EMAIL=${{ secrets.TEST_USER_EMAIL }} >> .env
          echo TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }} >> .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run format
      - run: npm run test
